config/routes.rb
Rails.application.routes.draw do
  resources :messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "messages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	def setMessageSubDate
		self.subdate = Time.now
		self.save	
	end
	def getMessageSubDate
		self.created_at		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all.order("created_at DESC")
    @message = Message.new
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to root_path}
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:message, :subdate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Messager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  
  </head>

  <body>
    <div>
      <script type="text/javascript">
        inicializa();
      </script>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_feed.html.erb
<div class="column">
	<div class="box">
		<article class="media box" id="no_border_shadow">
			<div class="media-content">
				<%= render 'form' %>
			</div>
		 </article>
	</div>
	<div class="box">
		<% @messages.each do | message | %>
		<div class="column">
			<div class="box">
				<p class="message_subdate">
				  <%= message.getMessageSubDate.to_date %>:
				</p>				
				<p class="message_text">
					
					<span id="<%= message.id %>"">
				  		<%= auto_link(message.message) %>
				  	</span>
				  	<script type="text/javascript">
					alteraMensagem("<%= message.id %>");

					</script>
				</p>
				<p class="message_text">
					<%= link_to 'Link', message_path(message) %> |
					<%= link_to 'Edit', edit_message_path(message) %> |
					<%= link_to 'Delete', message, method: :delete,remote: true %>
				</p>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/messages/_form.html.erb
<%= simple_form_for(@message) do |f| %>

<div class="field">
  <div class="control">
    <%= f.input :message, label: "Mensagem", input_html: {class: "textarea ",id:"meu-input"}, 
    wrapper: false, label_html: {class: "label"}, placeholder: "Escreva aqui: " %>
  </div>
</div>

<%= f.button :submit, class: "button is-info" %> 

<% end %>

app/views/messages/edit.html.erb
<section class="section">
  	<div class="container">
	    <div class="column">
	    	<div class="column">
				<div class="box">
					<article class="media box" id="no_border_shadow">
						<div class="media-content message_text">
							<%= render 'form', message: @message %>
							<%= link_to 'Show', @message %> |
							<%= link_to 'Back', messages_path %> |
							<%= link_to 'Delete', @message, method: :delete,remote: true %>
						</div>
					 </article>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/messages/index.html.erb
<section class="section">
  <div class="container">
    <div class="column">
      <%= render 'feed' %>
    </div>
  </div>
</section>

 

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<section class="section">
	<div class="container">
	    <div class="column">
	    	<div class="column">
				<div class="box">
					<p class="message_subdate">
					  <%= @message.getMessageSubDate.to_date %>
					  :
					</p>

					<p class="message_text">
					  <%= auto_link(@message.message) %>
					</p>
					<p class="message_text">
					<%= link_to 'Edit', edit_message_path(@message) %> |
					<%= link_to 'Back', messages_path %> |
					<%= link_to 'Delete', @message, method: :delete,remote: true %>
					</p>
				</div>
			</div>
		</div>
	</div>
</section>